WIP Transport_card
gfroidcourt/iut-onboarding pull request #27
Opened 2021-12-15 21:01 UTC by gfroidcourt

2021-12-16 09:32 UTC, celian-rib commented on src/components/TransportCard.vue
> +import RadialProgressBar from "../../node_modules//vue-radial-progress";
Quand tu va chercher une librairie qui se trouve dans node_modules le path n'est pas relatif
```suggestion
import RadialProgressBar from "vue-radial-progress";
```

2021-12-16 09:33 UTC, celian-rib commented on src/components/TransportCard.vue
> +      completed_steps: 1,
variable javascript => camelCase
```js
conpletedSteps
```

2021-12-17 19:25 UTC, gfroidcourt commented on src/components/TransportCard.vue
> +    async setTimeRemaining() {
Appeler cette méthode toutes les 10 secondes

2021-12-24 09:28 UTC, celian-rib requested changes

2021-12-24 09:28 UTC, celian-rib commented on package.json
> +    "vue3-circle-progress": "^1.0.7"
Faut supprimer celle qu'on utilise plus

2021-12-30 22:44 UTC, gfroidcourt commented
TODO: Gérer l'affichage dynamique des trams (comparer les données des bus et des trams et faire en fonction)

2022-01-25 13:16 UTC, killian-mannarelli approved these changes

2022-01-25 13:18 UTC, killian-mannarelli approved these changes

2022-01-25 13:26 UTC, killian-mannarelli approved these changes

2022-01-25 13:28 UTC, celian-rib requested changes

2022-01-25 13:28 UTC, celian-rib commented on src/components/TransportCard.vue
> +    },
Go hard coder la taille et ne pas faire passer en props

2022-01-25 13:36 UTC, killian-mannarelli approved these changes

2022-01-25 13:41 UTC, celian-rib requested changes

2022-01-25 13:41 UTC, celian-rib commented on src/components/TransportCard.vue
> +    },
ça degage

2022-01-25 13:41 UTC, celian-rib commented on src/components/TransportCard.vue
> +  box-shadow: 0px 0px 30px 0px rgba(30, 30, 30, 0.2);
faut le mettre LA

2022-01-25 14:05 UTC, celian-rib approved these changes

2022-01-25 14:06 UTC, merged