WIP Remplissage du JSON ok, intégration à l'appli Vue en cours
gfroidcourt/iut-onboarding pull request #28
Opened 2021-12-16 19:27 UTC by killian-mannarelli

2021-12-16 20:03 UTC, celian-rib requested changes
Faudrait enlever les changement du package-lock.json et le mettre en gitignore :)

2021-12-16 20:03 UTC, celian-rib commented on src/scrapMeal.js
> +  // } }
Prblm de CORS a régler :(

2021-12-16 20:19 UTC, celian-rib commented on src/scrapMeal.js
> +  // } }
@tjobit @gfroidcourt @gfroidcourt On va utiliser ça https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino
Le site n'a pas besoin d'etre utilisable par tous les navigateurs, donc dans le cadre du projet c'est OK

Pour résumer le problème :
Les navigateurs empêchent de faire une requête sur un site avec un nom de domaine différent pour des raisons de sécurité (CORS Policy). La vrai solution serait de proxier les requêtes sur un backend qui lui ne tourne pas dans un navigateur donc a le droit de get le site du crous.

2021-12-16 20:21 UTC, celian-rib requested changes

2021-12-16 20:21 UTC, celian-rib commented on src/scrapMeal.js
> +/* eslint-disable */
Faut enlever ca et corriger derrière toutes les erreurs @killian-mannarelli ou @tjobit

2021-12-17 22:07 UTC, celian-rib requested changes

2021-12-17 22:07 UTC, celian-rib commented on package.json
> +    "node-fetch": "^2.6.6",
Pas besoin de node-fetch au final, fetch est déjà intégré à node visiblement (Ya un fetch pour TBM dans api.js qui fonctionne très bien sans ce module)

2021-12-21 14:44 UTC, celian-rib requested changes

2021-12-21 14:44 UTC, celian-rib commented on src/scrapMeal.js
> +
ligne en trop

2021-12-21 14:44 UTC, celian-rib commented on src/scrapMeal.js
> +
ligne en trop

2021-12-21 14:46 UTC, killian-mannarelli commented on src/scrapMeal.js
> +
Done

2021-12-21 14:46 UTC, celian-rib approved these changes

2021-12-21 14:56 UTC, gfroidcourt approved these changes

2021-12-21 15:02 UTC, merged