MenuCard
gfroidcourt/iut-onboarding pull request #29
Opened 2021-12-17 16:44 UTC by tjobit

2021-12-18 22:05 UTC, celian-rib requested changes
Faudrait merge #28 avant, puis mettre main dans cette branche
+ Enlever les 15k changements du package-lock.json (Ce n'est pas normal d'en avoir autant)
+ Enlever les modifs du package.json

2021-12-18 22:11 UTC, celian-rib requested changes

2021-12-18 22:11 UTC, celian-rib commented on src/App.vue
> +      spaceMenu: "",
sirtakiMenu / spaceMenu son par définition des objets. Donc dans ce cas c'est mieux de mettre undefined

(Et faut bien gérer le cas où cette variable est undefined aux autres endroits :)

2021-12-18 22:11 UTC, celian-rib commented on src/components/MenuCard.vue
> +      <div id="meal" v-for="meal in mealList" :key="meal">- {{ meal }}</div>
### Exemple gestion undefined
Pour gérer le cas ou mealList peut être undefined
```suggestion
      <div id="meal" v-for="meal in mealList || []" :key="meal">- {{ meal }}</div>
```

2021-12-22 21:34 UTC, celian-rib approved these changes

2021-12-23 20:20 UTC, killian-mannarelli approved these changes

2021-12-23 20:21 UTC, merged