Fetch done. TODO: Fix HTML/CSS
gfroidcourt/iut-onboarding pull request #35
Opened 2022-01-26 15:41 UTC by gfroidcourt

2022-01-27 19:25 UTC, killian-mannarelli commented
Faut refactor le front non ?

2022-01-27 22:40 UTC, celian-rib commented
## Redesign

![image](https://user-images.githubusercontent.com/38594012/151455346-61c04188-3d75-43d1-a789-a59e4f2f80a8.png)

2022-01-28 09:56 UTC, killian-mannarelli requested changes
Enlève le commentaire grand fou va

2022-01-28 09:58 UTC, celian-rib approved these changes

2022-01-28 10:00 UTC, killian-mannarelli approved these changes

2022-01-28 10:00 UTC, merged