Loading bar
gfroidcourt/iut-onboarding pull request #63
Opened 2022-03-04 21:28 UTC by tjobit

2022-03-04 21:30 UTC, celian-rib requested changes

2022-03-04 21:30 UTC, celian-rib commented on src/components/LoadingBar.vue
> +  /*animation: progressing-vue linear infinite; */
dead

2022-03-04 21:30 UTC, celian-rib commented on src/components/LoadingBar.vue
> +*/
dead

2022-03-04 21:31 UTC, tjobit commented on src/App.vue
> +//import Planning from "./views/NextPlannings.vue";
```suggestion
import Planning from "./views/NextPlannings.vue";
```

2022-03-04 21:31 UTC, tjobit commented on src/App.vue
> +    //Planning,
```suggestion
    Planning,
```

2022-03-06 16:03 UTC, celian-rib requested changes
Beaucoup trop de changements ??? pourquoi

2022-03-07 09:46 UTC, celian-rib approved these changes

2022-03-07 09:47 UTC, killian-mannarelli approved these changes

2022-03-07 09:48 UTC, merged

2022-03-07 09:48 UTC, gfroidcourt approved these changes