Plannings only at the last 5 minutes of a break
gfroidcourt/iut-onboarding pull request #75
Opened 2022-03-16 21:59 UTC by killian-mannarelli

2022-03-17 06:51 UTC, gfroidcourt approved these changes

2022-03-17 09:29 UTC, celian-rib requested changes

2022-03-17 09:29 UTC, celian-rib commented on src/App.vue
> +          time: DEVELOPEMENT_MODE ? 5000 : returnTimeForPlanning(),
pas appeler la fonction dans data mais dans changeView() (+ il  manque le `this.`)

Ici le code est éxécuté quand App est rendu donc au début, alors que le code de changeView est éxécuté à intervalle régulier

2022-03-17 09:29 UTC, celian-rib commented on src/App.vue
> +          },
```suggestion
          allowed: () => true,
```

2022-03-17 09:29 UTC, celian-rib commented on src/App.vue
> +          },
```suggestion
          allowed: () => true,
```

2022-03-17 09:29 UTC, celian-rib commented on src/App.vue
> +            return currentHour >= 6 && currentHour < 14 && !this.onlyPlanning();
```suggestion
            return currentHour >= 6 && currentHour < 14;
```

2022-03-17 09:29 UTC, celian-rib commented on src/App.vue
> +    }
Utilise ESLint, la le code est mal format

2022-03-18 09:33 UTC, celian-rib commented
Demande de marius -> laisser aussi 5 minutes après les pauses pour les retardataires

2022-03-18 13:40 UTC, celian-rib commented
Réduire le temps du planning en temps normal pour compenser

2022-03-18 16:09 UTC, celian-rib approved these changes

2022-03-18 16:11 UTC, merged